# Generated by Django 5.2 on 2025-04-12 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Idade', models.IntegerField()),
                ('Aniversario', models.DateField()),
                ('Cadastro', models.DateField()),
                ('Ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.CharField(max_length=100)),
                ('Quantidade', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo_EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantidade_EPI', models.FloatField()),
                ('Data_Emprestimo', models.DateField()),
                ('Data_Devolucao', models.DateField()),
                ('Id_Colaborador', models.ManyToManyField(related_name='Colaborador', to='EPIS.colaborador')),
                ('Id_EPI', models.ManyToManyField(related_name='EPI', to='EPIS.epi')),
            ],
        ),
        migrations.AddField(
            model_name='epi',
            name='Tipo_EPI',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Tipo_EPI', to='EPIS.tipo_epi'),
        ),
    ]
