# Generated by Django 5.2 on 2025-04-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPIS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epi',
            name='Tipo_EPI',
        ),
        migrations.AddField(
            model_name='epi',
            name='Tipo_EPI',
            field=models.ManyToManyField(related_name='Tipo_EPI', to='EPIS.tipo_epi'),
        ),
    ]
