# Generated by Django 5.2 on 2025-04-12 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPIS', '0002_remove_epi_tipo_epi_epi_tipo_epi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epi',
            name='Tipo_EPI',
        ),
        migrations.AddField(
            model_name='epi',
            name='Tipo_EPI',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='epis', to='EPIS.tipo_epi'),
            preserve_default=False,
        ),
    ]
