# Generated by Django 5.2 on 2025-04-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EPIS', '0004_rename_data_devolucao_emprestimo_epi_data_devolucao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo_epi',
            name='data_emprestimo',
        ),
        migrations.RemoveField(
            model_name='emprestimo_epi',
            name='quantidade_epi',
        ),
    ]
