# Generated by Django 4.2.20 on 2025-04-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EPIS', '0005_remove_emprestimo_epi_data_emprestimo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epi',
            name='Quantidade',
        ),
    ]
