# Generated by Django 4.2.20 on 2025-04-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPIS', '0006_remove_epi_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo_epi',
            name='situacao',
            field=models.CharField(choices=[('ET', 'Entregue'), ('DV', 'Devolvido'), ('UT', 'Utilizando')], default='ET', max_length=3),
            preserve_default=False,
        ),
    ]
