# Generated by Django 4.2.20 on 2025-04-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPIS', '0007_emprestimo_epi_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo_epi',
            name='situacao',
            field=models.CharField(choices=[('1', 'Emprestado'), ('6', 'Perdido'), ('3', 'Fornecido'), ('2', 'Em Uso'), ('4', 'Devolvido'), ('5', 'Danificado')], max_length=3),
        ),
    ]
