# Generated by Django 4.2.20 on 2025-04-26 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EPIS', '0008_alter_emprestimo_epi_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo_epi',
            name='data_emprestimo',
            field=models.DateField(blank=True, default='2024-02-02'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='Cadastro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emprestimo_epi',
            name='data_devolucao',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='emprestimo_epi',
            name='situacao',
            field=models.CharField(choices=[('6', 'Perdido'), ('4', 'Devolvido'), ('5', 'Danificado'), ('2', 'Em Uso'), ('1', 'Emprestado'), ('3', 'Fornecido')], max_length=3),
        ),
    ]
