# Generated by Django 4.2.20 on 2025-04-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPIS', '0009_emprestimo_epi_data_emprestimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo_epi',
            name='situacao',
            field=models.CharField(choices=[('6', 'Perdido'), ('4', 'Devolvido'), ('5', 'Danificado'), ('2', 'Em Uso'), ('3', 'Fornecido'), ('1', 'Emprestado')], max_length=3),
        ),
    ]
