# Generated by Django 4.2.20 on 2025-04-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPIS', '0010_alter_emprestimo_epi_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo_epi',
            name='situacao',
            field=models.CharField(choices=[('5', 'Danificado'), ('2', 'Em Uso'), ('1', 'Emprestado'), ('3', 'Fornecido'), ('4', 'Devolvido'), ('6', 'Perdido')], max_length=3),
        ),
    ]
