# Generated by Django 4.2.20 on 2025-04-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPIS', '0011_alter_emprestimo_epi_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo_epi',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo_epi',
            name='data_emprestimo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo_epi',
            name='situacao',
            field=models.CharField(choices=[('5', 'Danificado'), ('6', 'Perdido'), ('3', 'Fornecido'), ('2', 'Em Uso'), ('1', 'Emprestado'), ('4', 'Devolvido')], max_length=3),
        ),
    ]
