# Generated by Django 4.2.20 on 2025-04-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EPIS', '0012_alter_emprestimo_epi_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo_epi',
            name='situacao',
            field=models.CharField(choices=[('5', 'Danificado'), ('1', 'Emprestado'), ('6', 'Perdido'), ('2', 'Em Uso'), ('3', 'Fornecido'), ('4', 'Devolvido')], max_length=3),
        ),
    ]
